name: Arcade action dev
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  EXECUTABLES:
    "arcade"

jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

  compilation:
    name: Compilation
    needs: clone
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          mkdir build && cd build
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          cd ..
          if [ -f "${{ env.EXECUTABLES}}" ]; then
            echo "Executable found"
            exit 0
          else
            ls -alF
            echo "Executable not found"
            echo "::error file="${{ env.EXECUTABLES}}",title=Binary::Binary not found"
            exit 1
          fi
